name: second workflow
# env var at workflow level example DOCKER_REGISTRY, DOCKER_USERNAME, IMAGE_NAME

env: 
    DOCKER_REGISTRY: docker.io
    DOCKER_USERNAME: devops1936
    IMAGE_NAME: nginx_gh_actions

on: push
# on: [push, fork]
jobs:
    build_job:
      runs-on: ubuntu-latest
      # env var at job level example docker_user not used in this examle
      env: 
        docker_user: aziz
      steps:
        - name: build
          run: echo docker build -t ${{env.DOCKER_REGISTRY}}/${{env.DOCKER_USERNAME}}/$IMAGE_NAME:latest
        
        - name: login
          env:
            # env var at steps level example DOCKER_PASSWORD
            DOCKER_PASSWORD: aa.bb.cc.dd
          run: echo docker login --username=${{env.DOCKER_USERNAME}} --password=$DOCKER_PASSWORD
        
        - name: publish
          run: echo docker push ${{env.DOCKER_REGISTRY}}/${{env.DOCKER_USERNAME}}/$IMAGE_NAME:latest
    
    deploy_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
          - name: run
            run: echo docker run -d -p 80:80 ${{env.DOCKER_REGISTRY}}/${{env.DOCKER_USERNAME}}/$IMAGE_NAME:latest
