name: myfirst workflow

on: push
# on: [push, fork]
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: using checkout action
              uses: actions/checkout@v4
            - name: cmd series
              run: |
                pwd
                echo -----------------------------------------------
                nproc
                echo -----------------------------------------------
                echo "this is my first github action" >hello.txt
                echo -----------------------------------------------
                ls -lta
                echo -----------------------------------------------
                cat README.md
