name: myfirst workflow

on: push
# on: [push, fork]
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: using checkout action
              uses: actions/checkout@v4
            - name: list and read files
              run: |
                echo "this is my first github action" | tee hello
                ls -lta
                head -n 10 README.md
