name: myfirst workflow

on: push
# on: [push, fork]
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: using checkout action
              uses: actions/checkout@v4
            - name: working directory
              run: pwd
            - name: nbre proc
              run: nproc
            - name: first github action
              run: echo "this is my first github action"
            
            - name: list folder
              run: ls 

            - name: cat file
              run: cat README.md
