name: using matrices include/exclude
on: push
jobs:
  deploy_on:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-20.04]
        image: [hello-world, alpine]
        exclude:
          - os: windows-latest
          - image: alpine
        include:
          - os: ubuntu-latest
          - image: amd64/alpine
    runs-on: ${{matrix.os}}
    steps:
      - name: run image on ${{matrix.os}}
        run: docker run ${{matrix.image}}

      - name: list container
        run: docker ps -l
  