name: using matrices
on: push
jobs:
  deploy_on:
    strategy:
      matrix:
        # version: [latest]
        # os: [ubuntu, windows]
        
        os: [ubuntu-latest, windows-latest]
        image: [hello-world, alpine]
    runs-on: ${{matrix.os}}
    
    # runs-on: ${{matrix.os}}-${{matrix.version}}

    steps:
      - name: run image on ${{matrix.os}}
        run: docker run ${{matrix.image}}

      - name: list container
        run: docker ps -l
  